# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
        # set reviewdoc version - fumi
        environment:
         REVIEWDOG_VERSION: 0.9.8
         GITHUB_API: https://api.github.com
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # install reviewdoc - fumi
      - run:
         name: install reviewdoc
         command: curl -fsL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      # install golint - fumi
      - run:
         name: install golint
         command: go get github.com/golang/lint/golint
      # install unused -fumi
      - run:
         name: install unused
         command: go get honnef.co/go/tools/cmd/unused

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      # - run: go test -v ./...
      # - run: go vet ./...
      # - run: gofmt -d .
      # - run: unused -help

      # - run: go test -run ''
      # - run: go test ./...
      - run: go tool vet -all -shadowstrict . 2>&1 | ./reviewdog -f=govet -ci="circle-ci"
      - run: golint ./... | ./reviewdog -f=golint -ci="circle-ci"

